# <span style="color:red; font-size:30px"> Project: Create a Data Structure to hold Voter Information </span>

<font size = "4">

Using the data structures and algorithms we have covered so far, you will implement a custom data structure for managing and analyzing voter data. It will be roughly analagous to a Pandas DataFrame (but you won't need to implement all the functionality that are provided by DataFrames!)

The basic functionality of your data structure can be demonstrated using the Pandas dataframe. In the cell below:

- Some synthetic voter data is generated

- The data is collected in a Pandas DataFrame, where each voter is stored as a single row.

In [1]:
from synthetic_data import *
import pandas as pd

# generate synthetic voter data
data = generate_dataset(n=10)
print(data)
# collect voters as rows
df = pd.DataFrame(data)

display(df)

[{'voter_id': 9773096970, 'age': 49, 'county': 'Gwinnett', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 0}, {'voter_id': 2207349866, 'age': 77, 'county': 'Gwinnett', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 1}, {'voter_id': 2814387754, 'age': 31, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 0}, {'voter_id': 7189417875, 'age': 31, 'county': 'Gwinnett', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1}, {'voter_id': 4178607036, 'age': 62, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 4132056461, 'age': 28, 'county': 'DeKalb', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 9279157138, 'age': 84, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0}, {'voter_id': 4444930625, 'age': 49, 'county': 'Clayton', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 1}, {'voter_id': 6743357253, 'age': 90, 'county': 'Clayton', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 0}, {'voter_id': 1171780928, 'age': 22, 'county': 'Cobb', 'party': 'Independent', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 0}]

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
1,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
4,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
5,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
6,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
7,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
8,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
9,1171780928,22,Cobb,Independent,>100K,1,1,0,0

In [3]:
data[1]

{'voter_id': 2207349866,
 'age': 77,
 'county': 'Gwinnett',
 'party': 'Democrat',
 'income_bracket': '50-100K',
 't_2016': 0,
 't_2018': 0,
 't_2020': 1,
 't_2022': 1}

<font size = "4">

- After creating the DataFrame, we may get new data, which can be added to the DataFrame.

In [4]:
# generate new data
new_data = generate_dataset(n=2)

# add it to the DataFrame as new rows
df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)

display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
1,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
4,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
5,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
6,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
7,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
8,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
9,1171780928,22,Cobb,Independent,>100K,1,1,0,0
10,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
11,6132158801,61,Clayton,Republican,<50K,1,1,1,1

<font size = "4">

- We can sort the rows of the DataFrame by any of the columns:

In [5]:
df.sort_values(by = "voter_id",inplace=True)
display(df)
print()
df.sort_values(by = "county",inplace=True)
display(df)

# ...or any of these other variables
df.sort_values(by = "age", inplace=True)
# df.sort_values(by="party",inplace=True)
# df.sort_values(by="income_bracket",inplace=True)
display(df)
# df.sort_values(by="t_2016",inplace=True)
# df.sort_values(by="t_2018",inplace=True)
# df.sort_values(by="t_2020",inplace=True)
# df.sort_values(by="t_2022",inplace=True)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
9,1171780928,22,Cobb,Independent,>100K,1,1,0,0
1,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
10,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
5,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
4,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
7,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
11,6132158801,61,Clayton,Republican,<50K,1,1,1,1
8,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
6,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
0,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
7,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
11,6132158801,61,Clayton,Republican,<50K,1,1,1,1
8,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
9,1171780928,22,Cobb,Independent,>100K,1,1,0,0
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
5,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
6,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
1,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
10,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
4,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
0,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
9,1171780928,22,Cobb,Independent,>100K,1,1,0,0
5,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
10,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
7,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
0,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
11,6132158801,61,Clayton,Republican,<50K,1,1,1,1
4,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
1,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
6,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
8,6743357253,90,Clayton,Democrat,>100K,1,0,1,0

<font size = "4">

- Even after sorting, we may receive new data. After adding this to the DataFrame, we need to re-sort.

In [6]:
# generate new data
new_data = generate_dataset(n=7)

df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)
display(df)
print()
df.sort_values(by = "age",inplace=True)
display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,1171780928,22,Cobb,Independent,>100K,1,1,0,0
1,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
4,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
5,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
6,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
7,6132158801,61,Clayton,Republican,<50K,1,1,1,1
8,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
9,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
10,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
11,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
12,4643764666,23,Gwinnett,Independent,<50K,0,0,0,1
13,6442358851,47,Fulton,Republican,50-100K,1,0,0,0
14,7083652750,75,DeKalb,Republican,50-100K,1,1,1,1
15,8694930002,63,Fulton,Democrat,<50K,1,1,1,1
16,9111879265,39,DeKalb,Independent,>100K,1,1,0,1
17,7602147501,81,Gwinnett,Democrat,50-100K,1,1,1,1
18,9670619696,27,Cobb,Democrat,<50K,1,0,1,0

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,1171780928,22,Cobb,Independent,>100K,1,1,0,0
12,4643764666,23,Gwinnett,Independent,<50K,0,0,0,1
18,9670619696,27,Cobb,Democrat,<50K,1,0,1,0
1,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
16,9111879265,39,DeKalb,Independent,>100K,1,1,0,1
4,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
13,6442358851,47,Fulton,Republican,50-100K,1,0,0,0
5,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
6,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
7,6132158801,61,Clayton,Republican,<50K,1,1,1,1
8,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
15,8694930002,63,Fulton,Democrat,<50K,1,1,1,1
14,7083652750,75,DeKalb,Republican,50-100K,1,1,1,1
9,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
17,7602147501,81,Gwinnett,Democrat,50-100K,1,1,1,1
10,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
11,6743357253,90,Clayton,Democrat,>100K,1,0,1,0

<font size = "4">

- We can sort by a value that does not explicitly appear as a column, but is defined by the data in each row:

In [8]:
# create temporary column
df["turnout_rate"] = df[["t_2016", "t_2018", "t_2020", "t_2022"]].sum(axis = 1) / 4

# sort by the temporary column
df.sort_values(by="turnout_rate",inplace=True)

# drop the temporary column
df.drop(columns="turnout_rate",inplace=True)
df

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
12,4643764666,23,Gwinnett,Independent,<50K,0,0,0,1
13,6442358851,47,Fulton,Republican,50-100K,1,0,0,0
0,1171780928,22,Cobb,Independent,>100K,1,1,0,0
9,2207349866,77,Gwinnett,Democrat,50-100K,0,0,1,1
6,9773096970,49,Gwinnett,Democrat,<50K,1,0,1,0
11,6743357253,90,Clayton,Democrat,>100K,1,0,1,0
18,9670619696,27,Cobb,Democrat,<50K,1,0,1,0
2,2814387754,31,DeKalb,Democrat,>100K,1,0,1,0
5,4444930625,49,Clayton,Democrat,<50K,1,1,0,1
10,9279157138,84,Fulton,Democrat,>100K,1,1,1,0
4,3973433514,47,Gwinnett,Republican,50-100K,0,1,1,1
16,9111879265,39,DeKalb,Independent,>100K,1,1,0,1
3,7189417875,31,Gwinnett,Democrat,<50K,1,0,1,1
14,7083652750,75,DeKalb,Republican,50-100K,1,1,1,1
1,4132056461,28,DeKalb,Republican,>100K,1,1,1,1
7,6132158801,61,Clayton,Republican,<50K,1,1,1,1
8,4178607036,62,Gwinnett,Republican,<50K,1,1,1,1
15,8694930002,63,Fulton,Democrat,<50K,1,1,1,1
17,7602147501,81,Gwinnett,Democrat,50-100K,1,1,1,1

<font size = "4">

- We can search for items in the DataFrame based on some condition:

In [9]:
# indices corresponding to voters older than 30
print("Indices corresponding to voters older than 30:")
print(df[df["age"] > 30].index.to_list())
print()
print("Indices corresponding to Fulton county voters:")
print(df[df["county"] == "Fulton"].index.to_list())

Indices corresponding to voters older than 30:
[13, 9, 6, 11, 2, 5, 10, 4, 16, 3, 14, 7, 8, 15, 17]

Indices corresponding to Fulton county voters:
[13, 10, 15]

# <span style="color:red; font-size:30px"> Your Task </span>

<font size = "4">

- Instead of storing the data as rows in a Pandas DataFrame, you will implement your own data structure, a *VoterRegistry* class. 

- Instead of storing data in rows, a VoterRegistry stores multiple Voter objects, which is implemented in the next cell.

In [32]:
class Voter:
    def __init__(self, voter_id, age, county, party, income_bracket, turnout_history):
        self.voter_id = voter_id
        self.age = age
        self.county = county
        self.party = party
        self.income_bracket = income_bracket
        self.turnout_history = turnout_history  # list of 0/1

    def turnout_rate(self):
        if not self.turnout_history:
            return 0.0
        return sum(self.turnout_history) / len(self.turnout_history)

    def __repr__(self):
        return (
            f"Voter(id={self.voter_id}, age={self.age}, "
            f"county='{self.county}', party='{self.party}', "
            f"income='{self.income_bracket}')"
        )

# Example use for one data point from a generated dataset
data = generate_dataset(n=100)
single_data_pt = data[0]
turn_out = [single_data_pt["t_2016"], single_data_pt["t_2018"],
    single_data_pt["t_2020"], single_data_pt["t_2022"]]

voter = Voter(single_data_pt["voter_id"],
            single_data_pt["age"],
            single_data_pt["county"],
            single_data_pt["party"],
            single_data_pt["income_bracket"],
            turn_out)

print(voter)
print(voter.turnout_rate())

Voter(id=9397565837, age=50, county='Gwinnett', party='Republican', income='>100K')
0.75

<font size = "4">

- Your VoterRegistry structure must store the Voter objects as either:

    - A collection of linked Nodes. (You may make any edits to the Node class you deem necessary).

    - A Hash Table. For simplicity, you are allowed to use Python lists here, but the index location must be determined by a hash function. 
    
- If you choose to implement a Hash Table, keep the following in mind:

    - We want to be able to add additional Voter objects when new data is generated, so the length of the Python list may need to be dynamically adjusted.

    - To resolve hash collisions, you can use rehashing or you can try chaining using a linked Node structure.

    - We can't "sort" a Hash Table, but you can sort a **view** of a Hash Table (a temporary contiguous array).

- Your VoterRegistry should perform the same basic tasks that we saw with the Pandas DataFrames above:

    - It can be initialized from the output of `generate_dataset`.

    - It can be sorted in ascending order by "voter_id", "age", "county", "party", "income_bracket" and the turnout for the years 2016, 2018, 2020, 2022.

    - It can be sorted in ascending order by the turnout rate. Note that this isn't an attribute of a Voter object, but can be calculated using the `turnout_rate` method.

    - New voter data can be added/appended to the VoterRegistry.

    - We can search for indices/locations corresponding to conditions based on the Voter attributes and standard Boolean comparison operators.

- Perform benchmarking, testing your searching and sorting methods. Try varying the size of the stored data and whether the data is already "almost" sorted or sorted in the opposite order. Summarize your results.

- To make your code and write-up as readable as possible, please include Markdown text describing your implementation decisions and what each object/method/function does.

# <span style="color:red; font-size:30px"> Rubric </span>

1. **Data Structure Design & Implementation (4 points)**: Correctly implements the required data structure (e.g., linked list or hash table), with well-defined classes and attributes that support all require voter fields.

2. **Data Addition & Storage (4 points)**: Successfully adds new voter records, maintains data integrity, and supports dynamic updates (e.g., appending and re-sorting)

3. **Sorting Functionality (4 points)**: Correctly sorts by any required "column" (attribute) and by the computed value of turnout rate.

4. **Search Functionality (3 points)**: Implements search by voter attributes and supports Boolean conditions.

5. **Testing, Demonstration, & Benchmarking (3 points)**: Demonstrates all features with clearly shown examples (e.g., different dataset sizes, re-sorting after additions) and includes benchmarking or performance discussion.

6. **Code Quality & Documentation (2 points)**: Code is clean, readable, well-organized, and clearly documented with Markdown explanations of design decisions.

I use a unordered list:

- `Voter` stores one person's fields
- `Node` wraps one `Voter`
- `VoterRegistry` stores the linked list
- `sort(by)` sorts by any required field
- `search(field, op, value)` handles Boolean conditions

I create a benchmark test:

- `make_almost_sorted_registry` creates almost sorted registry
- `make_reverse_sorted_registry` creates reverse sorted registry

- `benchmark_sort` test performance on random registry, almost sorted registry, and reverse sorted registry

- `benchmark_search` test two cases: voters older than 30, or county is Fulton

In [10]:
from synthetic_data import generate_dataset
import time
import operator
import random


class Voter:
    def __init__(self, voter_id, age, county, party, income_bracket, turnout_history):
        self.voter_id = voter_id
        self.age = age
        self.county = county
        self.party = party
        self.income_bracket = income_bracket
        self.turnout_history = turnout_history

    def turnout_rate(self):
        if len(self.turnout_history) == 0:
            return 0.0
        return sum(self.turnout_history) / len(self.turnout_history)

    def turnout_year(self, year):
        year_map = {2016: 0, 2018: 1, 2020: 2, 2022: 3}
        return self.turnout_history[year_map[year]]

    def to_dict(self):
        return {
            "voter_id": self.voter_id,
            "age": self.age,
            "county": self.county,
            "party": self.party,
            "income_bracket": self.income_bracket,
            "t_2016": self.turnout_history[0],
            "t_2018": self.turnout_history[1],
            "t_2020": self.turnout_history[2],
            "t_2022": self.turnout_history[3],
            "turnout_rate": self.turnout_rate()
        }

    def __repr__(self):
        return (
            f"Voter(id={self.voter_id}, age={self.age}, county='{self.county}', "
            f"party='{self.party}', income='{self.income_bracket}', "
            f"turnout={self.turnout_history})"
        )


class Node:
    def __init__(self, voter):
        self.voter = voter
        self.next = None

In [11]:
class VoterRegistry:

    def __init__(self, data=None):
        self.head = None
        self.tail = None
        self.size = 0 

        if data is not None:
            self.add_from_dataset(data)

    def __len__(self):
        return self.size

    def __iter__(self):
        current = self.head
        while current is not None:
            yield current.voter
            current = current.next

    def _record_to_voter(self, record):
        turnout_history = [
            record["t_2016"],
            record["t_2018"],
            record["t_2020"],
            record["t_2022"]
        ]
        return Voter(
            voter_id=record["voter_id"],
            age=record["age"],
            county=record["county"],
            party=record["party"],
            income_bracket=record["income_bracket"],
            turnout_history=turnout_history
        )

    def add_voter(self, voter):
        new_node = Node(voter)

        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:  # add to the tail instead of to the head
            self.tail.next = new_node
            self.tail = new_node

        self.size += 1

    def add_record(self, record): # convert to Voter, then add
        voter = self._record_to_voter(record)
        self.add_voter(voter)

    def add_from_dataset(self, data): # batch adding from dataset
        for record in data:
            self.add_record(record)

    def to_list(self): # turn voter to dictionary
        return [voter.to_dict() for voter in self]

    def show(self, n=None):
        rows = self.to_list()
        if n is not None:
            rows = rows[:n]
        for i, row in enumerate(rows):
            print(i, row)

    def _get_value(self, voter, by):   # return node data by all the variables
        if by == "voter_id":
            return voter.voter_id
        if by == "age":
            return voter.age
        if by == "county":
            return voter.county
        if by == "party":
            return voter.party
        if by == "income_bracket":
            return voter.income_bracket
        if by == "t_2016":
            return voter.turnout_history[0]
        if by == "t_2018":
            return voter.turnout_history[1]
        if by == "t_2020":
            return voter.turnout_history[2]
        if by == "t_2022":
            return voter.turnout_history[3]
        if by == "turnout_rate":
            return voter.turnout_rate()
        raise ValueError(f"Unsupported sort/search field: {by}")
    
    def sort(self, by):

        # insertion sort on linked list

        if self.head is None or self.head.next is None:
            return

        sorted_head = None
        current = self.head

        while current is not None:
            next_unsorted = current.next

            if sorted_head is None or self._get_value(current.voter, by) < self._get_value(sorted_head.voter, by):
                current.next = sorted_head
                sorted_head = current
            else:
                search = sorted_head
                while (
                    search.next is not None and
                    self._get_value(search.next.voter, by) <= self._get_value(current.voter, by)
                ):
                    search = search.next

                current.next = search.next
                search.next = current

            current = next_unsorted

        self.head = sorted_head

        # rebuild tail
        tail_finder = self.head
        while tail_finder.next is not None:
            tail_finder = tail_finder.next
        self.tail = tail_finder

    def search(self, field, op_string, value):
        # define operators
        ops = {
            "==": operator.eq,
            "!=": operator.ne,
            ">": operator.gt,
            ">=": operator.ge,
            "<": operator.lt,
            "<=": operator.le
        }

        if op_string not in ops:
            raise ValueError("Operator must be one of ==, !=, >, >=, <, <=")

        op_func = ops[op_string]
        matches = []

        index = 0
        current = self.head
        while current is not None:
            current_value = self._get_value(current.voter, field)
            if op_func(current_value, value):
                matches.append(index)
            current = current.next
            index += 1

        return matches

In [24]:
def make_almost_sorted_registry(n, by="age", swaps=10):
    data = generate_dataset(n=n)
    registry = VoterRegistry(data)
    registry.sort(by) 
    # create a sorted list, then randomly swap some rows for benchmark test on almost sorted registry
    rows = registry.to_list() 
    for _ in range(swaps):
        i = random.randint(0, len(rows) - 1)
        j = random.randint(0, len(rows) - 1)
        rows[i], rows[j] = rows[j], rows[i]

    new_registry = VoterRegistry(rows)
    return new_registry


def make_reverse_sorted_registry(n, by="age"):
    data = generate_dataset(n=n)
    rows = sorted(
        data,
        key=lambda x: (
            x["age"] if by == "age" else x[by]
        ),
        reverse=True
    )  
    return VoterRegistry(rows) # create a reverse sorted registry for benchmark test


def benchmark_sort(n_values, by="age"): # test 
    results = []

    for n in n_values:
        random_registry = VoterRegistry(generate_dataset(n=n))
        t0 = time.perf_counter()
        random_registry.sort(by)
        t1 = time.perf_counter()

        almost_registry = make_almost_sorted_registry(n=n, by=by, swaps=max(1, n // 100))
        t2 = time.perf_counter()
        almost_registry.sort(by)
        t3 = time.perf_counter()

        reverse_registry = make_reverse_sorted_registry(n=n, by=by)
        t4 = time.perf_counter()
        reverse_registry.sort(by)
        t5 = time.perf_counter()

        results.append({
            "n": n,
            "random_sort_seconds": t1 - t0,
            "almost_sorted_seconds": t3 - t2,
            "reverse_sorted_seconds": t5 - t4
        })

    return results


def benchmark_search(n_values):
    results = []

    for n in n_values:
        registry = VoterRegistry(generate_dataset(n=n))

        t0 = time.perf_counter()
        registry.search("age", ">", 30)
        t1 = time.perf_counter()

        t2 = time.perf_counter()
        registry.search("county", "==", "Fulton")
        t3 = time.perf_counter()

        results.append({
            "n": n,
            "search_age_gt_30_seconds": t1 - t0,
            "search_county_fulton_seconds": t3 - t2,
        })

    return results

In [13]:
# registry created directly from `generate_dataset` 
data = generate_dataset(n=10)
registry = VoterRegistry(data)

print("Registry size:", len(registry))
registry.show(10)

Registry size: 10
0 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 6778625255, 'age': 69, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
2 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
4 {'voter_id': 8632187961, 'age': 86, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.75}
5 {'voter_id': 1253455224, 'age': 53, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1, 'turnout_rate': 0.5}
6 {'voter_id': 5258422132, 'age': 56, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
7 {'voter_id': 2888136824, 'age': 49, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
8 {'voter_id': 6546524172, 'age': 67, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
9 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}

In [14]:
# add data

new_data = generate_dataset(n=3)
registry.add_from_dataset(new_data)

print("Registry size after adding new data:", len(registry))
registry.show(13)

Registry size after adding new data: 13
0 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 6778625255, 'age': 69, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
2 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
4 {'voter_id': 8632187961, 'age': 86, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.75}
5 {'voter_id': 1253455224, 'age': 53, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1, 'turnout_rate': 0.5}
6 {'voter_id': 5258422132, 'age': 56, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
7 {'voter_id': 2888136824, 'age': 49, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
8 {'voter_id': 6546524172, 'age': 67, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
9 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
10 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
11 {'voter_id': 1235757391, 'age': 49, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
12 {'voter_id': 7362785272, 'age': 30, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}

In [15]:
# sort
registry.sort("voter_id")
print("Sorted by voter_id")
registry.show(8)

print()
registry.sort("county")
print("Sorted by county")
registry.show(8)

print()
registry.sort("age")
print("Sorted by age")
registry.show(8)

print()
registry.sort("turnout_rate")
print("Sorted by turnout_rate")
registry.show(8)

Sorted by voter_id
0 {'voter_id': 1235757391, 'age': 49, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 1253455224, 'age': 53, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1, 'turnout_rate': 0.5}
2 {'voter_id': 2888136824, 'age': 49, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
3 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
4 {'voter_id': 5258422132, 'age': 56, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
5 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
6 {'voter_id': 6546524172, 'age': 67, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
7 {'voter_id': 6778625255, 'age': 69, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}

Sorted by county
0 {'voter_id': 1235757391, 'age': 49, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 6546524172, 'age': 67, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
2 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
3 {'voter_id': 8632187961, 'age': 86, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.75}
4 {'voter_id': 2888136824, 'age': 49, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
5 {'voter_id': 5258422132, 'age': 56, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1, 'turnout_rate': 1.0}
6 {'voter_id': 1253455224, 'age': 53, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1, 'turnout_rate': 0.5}
7 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}

Sorted by age
0 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
2 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 7362785272, 'age': 30, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
4 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
5 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}
6 {'voter_id': 1235757391, 'age': 49, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
7 {'voter_id': 2888136824, 'age': 49, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}

Sorted by turnout_rate
0 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
1 {'voter_id': 7362785272, 'age': 30, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
2 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
4 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
5 {'voter_id': 1235757391, 'age': 49, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
6 {'voter_id': 1253455224, 'age': 53, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1, 'turnout_rate': 0.5}
7 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}

In [16]:
# search for items based on some condition

print("Locations where age > 30:")
print(registry.search("age", ">", 30))

print()
print("Locations where county == 'Fulton':")
print(registry.search("county", "==", "Fulton"))

Locations where age > 30:
[4, 5, 6, 7, 8, 9, 10, 11, 12]

Locations where county == 'Fulton':
[0, 2, 3, 4, 6, 12]

In [18]:
# add data and resort 

more_data = generate_dataset(n=3)
registry.add_from_dataset(more_data)

print("After adding more data")
registry.show(8)

print()
registry.sort("age")
print("Re-sorted by age")
registry.show(8)

After adding more data
0 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
2 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 3057419340, 'age': 26, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.5}
4 {'voter_id': 1918281535, 'age': 29, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.5}
5 {'voter_id': 7362785272, 'age': 30, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
6 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
7 {'voter_id': 8534752224, 'age': 44, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 1, 't_2022': 1, 'turnout_rate': 0.75}

Re-sorted by age
0 {'voter_id': 7518761328, 'age': 21, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
1 {'voter_id': 5232725960, 'age': 22, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
2 {'voter_id': 9707784787, 'age': 26, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.25}
3 {'voter_id': 3057419340, 'age': 26, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.5}
4 {'voter_id': 1918281535, 'age': 29, 'county': 'Fulton', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.5}
5 {'voter_id': 7362785272, 'age': 30, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0, 'turnout_rate': 0.0}
6 {'voter_id': 5561012404, 'age': 34, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}
7 {'voter_id': 5872910037, 'age': 35, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 1, 't_2022': 0, 'turnout_rate': 0.25}

Benchmark sorting and searching

In [21]:

sort_results = benchmark_sort([100, 200, 500, 1000, 2000], by="age")
for row in sort_results:
    print(row)

{'n': 100, 'random_sort_seconds': 0.0004517999477684498, 'almost_sorted_seconds': 0.0006972998380661011, 'reverse_sorted_seconds': 2.8100330382585526e-05}
{'n': 200, 'random_sort_seconds': 0.001389200333505869, 'almost_sorted_seconds': 0.002835799939930439, 'reverse_sorted_seconds': 9.450037032365799e-05}
{'n': 500, 'random_sort_seconds': 0.009533599950373173, 'almost_sorted_seconds': 0.018020099960267544, 'reverse_sorted_seconds': 0.0005290997214615345}
{'n': 1000, 'random_sort_seconds': 0.041557599790394306, 'almost_sorted_seconds': 0.06150539964437485, 'reverse_sorted_seconds': 0.0010202997364103794}
{'n': 2000, 'random_sort_seconds': 0.12759010028094053, 'almost_sorted_seconds': 0.22913149977102876, 'reverse_sorted_seconds': 0.0035828999243676662}

reverse sorted list is the fastest because adding item is to the tail.

In [25]:
search_results = benchmark_search([100, 300, 500, 800, 1000,2000])
for row in search_results:
    print(row)

{'n': 100, 'search_age_gt_30_seconds': 1.859990879893303e-05, 'search_county_fulton_seconds': 1.0999850928783417e-05}
{'n': 300, 'search_age_gt_30_seconds': 3.260001540184021e-05, 'search_county_fulton_seconds': 2.9299873858690262e-05}
{'n': 500, 'search_age_gt_30_seconds': 5.4900068789720535e-05, 'search_county_fulton_seconds': 5.189981311559677e-05}
{'n': 800, 'search_age_gt_30_seconds': 9.079976007342339e-05, 'search_county_fulton_seconds': 8.030002936720848e-05}
{'n': 1000, 'search_age_gt_30_seconds': 0.00011059967800974846, 'search_county_fulton_seconds': 0.00010350020602345467}
{'n': 2000, 'search_age_gt_30_seconds': 0.00021990016102790833, 'search_county_fulton_seconds': 0.0002083997242152691}